---Highest 10 and lowest 10 MOVIES---
SELECT * FROM (SELECT A.TITLE,
	SUM(D.AMOUNT) AS "Total sale"
FROM FILM A
LEFT JOIN INVENTORY B ON A.FILM_ID = B.FILM_ID
INNER JOIN RENTAL C ON B.INVENTORY_ID = C.INVENTORY_ID
INNER JOIN PAYMENT D ON C.RENTAL_ID = D.RENTAL_ID
GROUP BY A.FILM_ID,
	A.TITLE
ORDER BY 2 DESC
LIMIT 10) AS HIGHEST
UNION
SELECT * FROM (SELECT 	A.TITLE,
	SUM(D.AMOUNT) AS "Total sale"
FROM FILM A
LEFT JOIN INVENTORY B ON A.FILM_ID = B.FILM_ID
INNER JOIN RENTAL C ON B.INVENTORY_ID = C.INVENTORY_ID
INNER JOIN PAYMENT D ON C.RENTAL_ID = D.RENTAL_ID
GROUP BY A.FILM_ID,
	A.TITLE
ORDER BY 2
LIMIT 10) AS LOWEST ORDER BY 2 DESC;

--- Renting distribution ACROSS movie categories--
SELECT c.name AS "Movie Category",COUNT(E.RENTAL_ID)"TOTAL_RENTALS", SUM(F.AMOUNT)"TOTAL SALES",
	ROUND(AVG(A.RENTAL_DURATION),
		2) AS "Average Rental Duration",
	MAX(A.RENTAL_DURATION) AS "Maximum Rental Duration",
	MIN(A.RENTAL_DURATION) AS "Minimum Rental Duration",
	ROUND(AVG(A.RENTAL_RATE),
		2) AS "Average Rental Rate",
	MAX(A.RENTAL_RATE)AS  "Maximum Rental Rate",
	MIN(A.RENTAL_RATE)AS "Minimum Rental Rate"
FROM FILM A
INNER JOIN FILM_CATEGORY B ON A.FILM_ID=B.FILM_ID
INNER JOIN CATEGORY C ON B.CATEGORY_ID=C.CATEGORY_ID 
INNER JOIN INVENTORY D ON A.FILM_ID=D.FILM_ID
INNER JOIN RENTAL E ON D.INVENTORY_ID=E.INVENTORY_ID
INNER JOIN PAYMENT F ON E.RENTAL_ID=F.RENTAL_ID
GROUP BY c.name ORDER BY 3 DESC;



---High value customers---
WITH HIGH_CUS_VAL_CTE(CUSTOMER_ID,COUNTRY,TOTAL_AMOUNT) AS(SELECT A.CUSTOMER_ID,
	D.COUNTRY,
	ROUND(SUM(AMOUNT),
		2) "TOTAL_AMOUNT"
FROM CUSTOMER A
INNER JOIN PAYMENT E ON A.CUSTOMER_ID = E.CUSTOMER_ID
LEFT JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
GROUP BY D.COUNTRY,
	A.CUSTOMER_ID
ORDER BY 6 DESC LIMIT 10);


---COUNTRY WISE SALES AND CUSTOMER COUNT----

SELECT 
	D.COUNTRY,
	ROUND(SUM(AMOUNT),
		2) "TOTAL SALES AMOUNT",COUNT(DISTINCT A.CUSTOMER_ID) AS "TOTAL_CUSOTMER"
FROM CUSTOMER A
INNER JOIN PAYMENT E ON A.CUSTOMER_ID = E.CUSTOMER_ID
INNER JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
GROUP BY D.COUNTRY
ORDER BY 2 DESC;



------rental details------

SELECT 	ROUND(AVG(A.RENTAL_DURATION),0) AS "Average Rental Duration",
	MAX(A.RENTAL_DURATION) AS "Maximum Rental Duration",
	MIN(A.RENTAL_DURATION) AS "Minimum Rental Duration",
	ROUND(AVG(A.RENTAL_RATE),
		2) AS "Average Rental Rate",
	MAX(A.RENTAL_RATE)AS  "Maximum Rental Rate",
	MIN(A.RENTAL_RATE)AS "Minimum Rental Rate"
FROM FILM A;



--countrywise customer distribution,sales and high value customer-----
WITH HIGH_CUS_VAL_CTE(CUSTOMER_ID,COUNTRY,TOTAL_AMOUNT) AS(SELECT A.CUSTOMER_ID,
	D.COUNTRY,
	ROUND(SUM(AMOUNT),
		2) "TOTAL_AMOUNT"
FROM CUSTOMER A
INNER JOIN PAYMENT E ON A.CUSTOMER_ID = E.CUSTOMER_ID
LEFT JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
GROUP BY D.COUNTRY,
	A.CUSTOMER_ID
ORDER BY 3 DESC LIMIT 10)
SELECT 
	D.COUNTRY,
	ROUND(SUM(AMOUNT),
		2) "TOTAL SALES AMOUNT",COUNT(DISTINCT A.CUSTOMER_ID) AS "TOTAL_CUSOTMER",
		COUNT(DISTINCT F.CUSTOMER_ID) AS "HIGH VALUE CUSTOMER COUNT"
FROM CUSTOMER A
INNER JOIN PAYMENT E ON A.CUSTOMER_ID = E.CUSTOMER_ID
INNER JOIN ADDRESS B ON A.ADDRESS_ID = B.ADDRESS_ID
INNER JOIN CITY C ON B.CITY_ID = C.CITY_ID
INNER JOIN COUNTRY D ON C.COUNTRY_ID = D.COUNTRY_ID
LEFT JOIN HIGH_CUS_VAL_CTE F ON D.COUNTRY=F.COUNTRY
GROUP BY D.COUNTRY
ORDER BY 2 DESC;
